export const UPDATE_QUERY = 'UPDATE_QUERY';
export const UPDATE_LOCATION_QUERY = 'UPDATE_LOCATION_QUERY';
// export const CLEAR_LOCATION_RESULTS = 'CLEAR_LOCATION_RESULTS';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const CLEAR_LOCATION_RESULTS = 'CLEAR_LOCATION_RESULTS';

export const UPDATE_ENTITY_TYPE = 'UPDATE_ENTITY_TYPE';
// locations.js
export const LOCATION_SEARCH_REQUEST = 'LOCATION_SEARCH_REQUEST';
export const LOCATION_SEARCH_SUCCESS = 'LOCATION_SEARCH_SUCCESS';
export const LOCATION_SEARCH_FAILURE = 'LOCATION_SEARCH_FAILURE';

// restaurant.js
export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
export const FETCH_RESTAURANTS_SUCCESS = ' FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAILURE = ' FETCH_RESTAURANTS_FAILURE';

// loadMore.js
export const LOAD_MORE_REQUEST = 'LOAD_MORE_REQUEST';
export const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';
export const LOAD_MORE_FAILURE = 'LOAD_MORE_FAILURE';